
DROP TABLE IF EXISTS nanchang_alldata;

CREATE table if not exists nanchang_alldata(
	USERID VARCHAR(255) PRIMARY KEY,
	STARTIME VARCHAR(255),
	SDRTYPE INT2,
	CGI INT8,
	LONGITUDE FLOAT8,
	LATITUDE FLOAT8,
	RANTYPE INT2
);

INSERT INTO "tianyeyoumin"."nanchang_alldata" ("USERID", "STARTTIME", "SDRTYPE", "CGI", "LONGITUDE", "LATITUDE", "RANTYPE")
SELECT "USERID", "STARTTIME", "SDRTYPE", "CGI", "LONGITUDE", "LATITUDE", "RANTYPE"
FROM (
    SELECT "USERID", "STARTTIME", "SDRTYPE", "CGI", "LONGITUDE", "LATITUDE", "RANTYPE" FROM "public"."nc_20150511"
    UNION ALL
    SELECT "USERID", "STARTTIME", "SDRTYPE", "CGI", "LONGITUDE", "LATITUDE", "RANTYPE" FROM "public"."nc_20150512"
    UNION ALL
    SELECT "USERID", "STARTTIME", "SDRTYPE", "CGI", "LONGITUDE", "LATITUDE", "RANTYPE" FROM "public"."nc_20150513"
    UNION ALL
    SELECT "USERID", "STARTTIME", "SDRTYPE", "CGI", "LONGITUDE", "LATITUDE", "RANTYPE" FROM "public"."nc_20150514"
    UNION ALL
    SELECT "USERID", "STARTTIME", "SDRTYPE", "CGI", "LONGITUDE", "LATITUDE", "RANTYPE" FROM "public"."nc_20150515"
    UNION ALL
    SELECT "USERID", "STARTTIME", "SDRTYPE", "CGI", "LONGITUDE", "LATITUDE", "RANTYPE" FROM "public"."nc_20150516"
    UNION ALL
    SELECT "USERID", "STARTTIME", "SDRTYPE", "CGI", "LONGITUDE", "LATITUDE", "RANTYPE" FROM "public"."nc_20150517"
) AS combined_data;
