-- 创建新表来存储OD数据
DROP TABLE IF EXISTS nc_3_5_od_flow;
CREATE TABLE IF NOT EXISTS nc_3_5_od_flow (
    "HOME_LONGITUDE" FLOAT,
    "HOME_LATITUDE" FLOAT,
    "WORK_LONGITUDE" FLOAT,
    "WORK_LATITUDE" FLOAT,
    "FLOW_COUNT" INT
);

-- 插入数据：统计从每个居住地到每个工作地的人数
INSERT INTO nc_3_5_od_flow
SELECT 
    "HOME_LONGITUDE",
    "HOME_LATITUDE",
    "WORK_LONGITUDE",
    "WORK_LATITUDE",
    COUNT(*) AS "FLOW_COUNT"
FROM 
    nc_3_3_user_work_home_location
GROUP BY 
    "HOME_LONGITUDE", "HOME_LATITUDE", "WORK_LONGITUDE", "WORK_LATITUDE";

-- 创建索引以提高查询性能
CREATE INDEX idx_od_flow ON nc_3_5_od_flow ("HOME_LONGITUDE", "HOME_LATITUDE", "WORK_LONGITUDE", "WORK_LATITUDE");

-- 查询结果
SELECT * FROM nc_3_5_od_flow
ORDER BY "FLOW_COUNT" DESC
LIMIT 10;

-- 统计总流动量
SELECT SUM("FLOW_COUNT") AS "TOTAL_FLOW" FROM nc_3_5_od_flow;

-- 统计不同的起始点和终点数量
SELECT 
    COUNT(DISTINCT ("HOME_LONGITUDE", "HOME_LATITUDE")) AS "UNIQUE_ORIGINS",
    COUNT(DISTINCT ("WORK_LONGITUDE", "WORK_LATITUDE")) AS "UNIQUE_DESTINATIONS"
FROM nc_3_5_od_flow;